// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmOnttDydnUJ-ZDIpUJS2h4lNIKNifmVI',
    appId: '1:457039953803:android:76c7f6c02c468db98db98e',
    messagingSenderId: '457039953803',
    projectId: 'musicapp-d8345',
    storageBucket: 'musicapp-d8345.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeVdLS-kRh89cuZLrOhY0K0CTwj9qi5ss',
    appId: '1:457039953803:ios:f221002bc8f84d178db98e',
    messagingSenderId: '457039953803',
    projectId: 'musicapp-d8345',
    storageBucket: 'musicapp-d8345.appspot.com',
    androidClientId: '457039953803-7aht1j92p75oi7roovtpjb3kr9medn9l.apps.googleusercontent.com',
    iosClientId: '457039953803-tu7tv0steuo1pf9fst4pcq2h15vbg8u6.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicapp',
  );
}
